### ISSUE TITLE
be able to configure the port and listen to inet_addr_any

### ISSUE THREAD

**Issue by tcoopman** [yawaramin/re-web#16]
I've been playing with `re-web` and enjoying it so far. One of the things I was trying to do was to play with a build in docker, but found out it didn't work because the server needs to listen to `inet_addr_any` instead of `inet_addr_loopback`.

I have changed this in a branch on my fork: https://github.com/yawaramin/re-web/compare/master...tcoopman:inet_addr_any?expand=1

I can create a PR if you give me some insights in how you would want this to be configured.

You probably want to add something in the `Config` module?

**Comment by yawaramin** [comment]
Cool, please do send a PR when you can :-) the port is configurable currently from `Server.serve ?port server`, but it would be cool to have it as a config.

**Comment by yawaramin** [comment]
Fixed by #17
