### ISSUE TITLE
Unable to load compilation data: No root directory found

### ISSUE THREAD

**Issue by hartmut27** [yawaramin/re-web#24]
I am using `VS Code` with extension `reason-vscode` Reason Language Server (RLS).
I cloned the `re-web` demo application with `git clone https://github.com/yawaramin/fullstack-reason.git test01`. OCaml native backend end NPM reason frontend both work very well, this is very encouraging :)

The non-critical problem: In file `backend/App.re`, when I navigate to `open ReWeb;` (see screenshot), `reWeb.ml` is opened. Starting from here, I can't lookup the symbols because of "No root directory found" in `VS Code`'s error message.

The problem does not relate to ReWeb directly,  sure the origin lies more in Reason Language Server's handling of native `esy` compiled ocaml-files, but I could find a solution yet.

If anybody have found an work-around, please let me know.
No problem if you close this issue, then it could be used for reference reasons - then perhaps it helps other people wanting get in touch ReWeb and search a way around this problem.

Following RLS issues are relating (not solved yet): [162](https://github.com/jaredly/reason-language-server/issues/162), [177](https://github.com/jaredly/reason-language-server/issues/177), [334](https://github.com/jaredly/reason-language-server/issues/334)

![image](https://user-images.githubusercontent.com/752620/78052504-88b7a900-737f-11ea-8217-869d7361854c.png)
![image](https://user-images.githubusercontent.com/752620/78052516-8bb29980-737f-11ea-8f98-affcb15e6b0b.png)

**Comment by yawaramin** [comment]
Hi, thanks for trying it out :-) I think this is a general problem with OCaml tooling–editor support tools only work within the project itself, not on dependencies. See this thread: https://discuss.ocaml.org/t/merlin-goto-definition-inside-installed-libraries/2788
