### ISSUE TITLE
current version of h2 seems to fail

### ISSUE THREAD

**Issue by tcoopman** [yawaramin/re-web#27]
with this error:

```
info building @reason-native-web/h2@0.6.0@d41d8cd9
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @reason-native-web/h2@0.6.0
    # esy-build-package: pwd: /home/thomas/.esy/source/i/reason_native_web__s__h2__0.6.0__c2f59108
    # esy-build-package: running: 'dune' 'build' '--only-packages=h2' '--profile=release' '-j' '4' '--root=./ocaml-h2'
    Entering directory '/home/thomas/.esy/source/i/reason_native_web__s__h2__0.6.0__c2f59108/ocaml-h2'
    File "lib/settings.ml", line 290, characters 7-28:
    290 |        Angstrom.parse_string
                 ^^^^^^^^^^^^^^^^^^^^^
    Error: This function has type 'a Angstrom.t -> string -> ('a, string) result
           It is applied to too many arguments; maybe you forgot a `;'.
    error: command failed: 'dune' 'build' '--only-packages=h2' '--profile=release' '-j' '4' '--root=./ocaml-h2' (exited with 1)
    esy-build-package: exiting with errors above...
    
  building @reason-native-web/h2@0.6.0
```

got this error when building `fullstack-reason` after removing `esy.lock`

**Comment by tcoopman** [comment]
It seems `h2` needs `Angstrom` >= 0.14 (see https://github.com/anmonteiro/ocaml-h2/blob/master/h2.opam)

**Comment by tcoopman** [comment]
I was trying to make a quick PR, but it seems like there were a bunch of changes in `piaf`/`h2`/... so it's probably something you have a look at :-)

**Comment by yawaramin** [comment]
Yeah 🙂 there's been a bunch of changes in the vendored upstream packages, I'm getting a build error on my end too (sent a PR: https://github.com/anmonteiro/websocketaf/pull/14 ). Let me see if I can find another way...

**Comment by yawaramin** [comment]
I just upgraded the libraries and pushed 0765585, let me know if that works.

**Comment by tcoopman** [comment]
with the new resolutions it works.
I'll see if I can send a PR later to the fullstack example so that it works again as well
