### ISSUE TITLE
Getting "Error: Program "examples/1_hello_world/Main.bc" not found!" when running examples

### ISSUE THREAD

**Issue by jplew** [yawaramin/re-web#33]
Please forgive me if this is a dumb question, I'm new to this ecosystem.

While attempting to run an example from the root of the repo, I get this error:

```shell
~/Sites/projects/re-web $ esy run-example examples/1_hello_world/Main.bc                                                                
Error: Program "examples/1_hello_world/Main.bc" not found!
```

In contrast, when I run `esy run-example examples/1_hello_world/Main.exe`, it works. 

I looked it up in the Dune docs (https://dune.readthedocs.io/en/latest/dune-files.html?highlight=.bc#executable), but was unable to figure out how to build a byte-code executable.

**Comment by yawaramin** [comment]
Ah, thanks for pointing this out. I had forgotten to update the examples when I upgraded to Dune version 2. Fixing now.
